# Generated by Django 6.1 on 2026-09-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=255)),
                ('nit_entidad', models.CharField(max_length=50)),
                ('departamento', models.CharField(db_index=True, max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('id_contrato', models.CharField(max_length=100, unique=True)),
                ('estado_contrato', models.CharField(max_length=100)),
                ('codigo_categoria_principal', models.CharField(max_length=100)),
                ('descripcion_del_proceso', models.TextField()),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_firma', models.DateField()),
                ('modalidad', models.CharField(db_index=True, max_length=100)),
                ('contratista_nit', models.CharField(db_index=True, max_length=50)),
                ('contratista_nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
