# Generated by Django 6.1 on 2026-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['departamento'], name='idx_contrato_depto'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['modalidad'], name='idx_contrato_modalidad'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['fecha_firma'], name='idx_contrato_fecha'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['contratista_nit'], name='idx_contrato_nit'),
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contrato',
        ),
    ]
