# Generated by Django 6.1 on 2026-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_idx_contrato_depto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='contratista_nit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='modalidad',
            field=models.CharField(max_length=100),
        ),
    ]
