# Generated by Django 6.1 on 2026-09-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_contratista_nit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=255)),
                ('nit_entidad', models.CharField(max_length=50, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'entidad',
                'indexes': [models.Index(fields=['nit_entidad'], name='idx_entidad_nit')],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='contratos.entidad'),
        ),
    ]
