# Generated by Django 6.1 on 2026-09-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_entidad_contrato_entidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('offset_actual', models.IntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trabajo_carga',
                'ordering': ['-creado_en'],
            },
        ),
    ]
