# Generated by Django 6.1 on 2026-09-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_trabajocarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'umbral_alerta',
            },
        ),
    ]
