# Generated by Django 6.1 on 2026-09-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_umbralalerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_horas', models.IntegerField(default=24)),
                ('activo', models.BooleanField(default=False)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_estado', models.CharField(blank=True, default='', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'config_actualizacion',
            },
        ),
        migrations.AddField(
            model_name='trabajocarga',
            name='nuevos_registros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trabajocarga',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('periodica', 'Periódica')], default='manual', max_length=20),
        ),
    ]
