# Generated by Django 6.1 on 2026-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_configactualizacion_trabajocarga_nuevos_registros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('tamaño_bytes', models.IntegerField(default=0)),
                ('registros', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('error', 'Error')], default='completado', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'backup_registro',
                'ordering': ['-creado_en'],
            },
        ),
    ]
