# Generated by Django 6.1 on 2026-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_backupregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('accion', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('exportar', 'Exportar'), ('config_umbral', 'Config umbral'), ('backup', 'Backup'), ('carga', 'Carga')], max_length=20)),
                ('detalle', models.CharField(blank=True, default='', max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-fecha'],
            },
        ),
    ]
