# Generated by Django 6.1 on 2026-09-18 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_objetivo', models.CharField(blank=True, default='', max_length=100)),
                ('palabras_clave', models.CharField(max_length=255)),
                ('rango_cuantia_min', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rango_cuantia_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'radar',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Nueva', 'Nueva'), ('Guardada', 'Guardada'), ('Postulado', 'Postulado')], default='Nueva', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='contratos.contrato')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='contratos.radar')),
            ],
            options={
                'db_table': 'oportunidad',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='radar',
            index=models.Index(fields=['usuario'], name='idx_radar_usuario'),
        ),
        migrations.AddIndex(
            model_name='radar',
            index=models.Index(fields=['palabras_clave'], name='idx_radar_palabras'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['radar', 'estado'], name='idx_oportunidad_radar_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='oportunidad',
            unique_together={('contrato', 'radar')},
        ),
    ]
