# Generated by Django 6.1 on 2026-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_radar_oportunidad_radar_idx_radar_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='filtros_extras',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
