# Generated by Django 6.1 on 2026-09-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_radar_filtros_extras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupregistro',
            old_name='tamaño_bytes',
            new_name='tamano_bytes',
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('exportar', 'Exportar'), ('config_umbral', 'Config umbral'), ('backup', 'Backup'), ('carga', 'Carga'), ('reset_password', 'Reset password')], max_length=20),
        ),
    ]
