# Generated by Django 6.1 on 2026-10-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_backup_tamano_ascii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id_contrato',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
