# Generated by Django 6.1 on 2026-10-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_indices_covering_9m'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDepto',
            fields=[
                ('departamento', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total', models.BigIntegerField(default=0)),
                ('suma', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('directas', models.BigIntegerField(default=0)),
                ('suma_directa', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'resumen_depto',
            },
        ),
        migrations.CreateModel(
            name='ResumenGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0)),
                ('suma', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resumen_global',
            },
        ),
        migrations.CreateModel(
            name='SerieMensual',
            fields=[
                ('mes', models.DateField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField(default=0)),
                ('suma', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'serie_mensual',
                'ordering': ['mes'],
            },
        ),
        migrations.CreateModel(
            name='ContratistaTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratista_nit', models.CharField(max_length=50)),
                ('contratista_nombre', models.CharField(max_length=255)),
                ('total_contratos', models.BigIntegerField(default=0)),
                ('suma_valor', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'contratista_total',
                'indexes': [models.Index(fields=['-suma_valor'], name='idx_ctop_suma')],
            },
        ),
    ]
