# Generated by Django 6.1 on 2026-10-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_resumenes_precalculados_v34'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieDepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('mes', models.DateField()),
                ('total', models.BigIntegerField(default=0)),
                ('suma', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'serie_depto',
                'ordering': ['departamento', 'mes'],
                'unique_together': {('departamento', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='TopDepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('contratista_nit', models.CharField(max_length=50)),
                ('contratista_nombre', models.CharField(max_length=255)),
                ('total_contratos', models.BigIntegerField(default=0)),
                ('suma_valor', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'top_depto',
                'indexes': [models.Index(fields=['departamento', '-suma_valor'], name='idx_topdepto_depto')],
            },
        ),
    ]
