# Generated by Django 6.1 on 2026-10-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_top_serie_depto_v34'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanderaDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('nombre_entidad', models.CharField(max_length=255)),
                ('contratista_nit', models.CharField(max_length=50)),
                ('contratista_nombre', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('contratos', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'bandera_det',
                'indexes': [models.Index(fields=['departamento', '-monto'], name='idx_bdet_depto'), models.Index(fields=['-monto'], name='idx_bdet_monto')],
            },
        ),
        migrations.CreateModel(
            name='EntidadDepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('nombre_entidad', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'entidad_depto',
                'unique_together': {('departamento', 'nombre_entidad')},
            },
        ),
        migrations.CreateModel(
            name='PredominioEnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('nombre_entidad', models.CharField(max_length=255)),
                ('total', models.BigIntegerField(default=0)),
                ('directas', models.BigIntegerField(default=0)),
                ('pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('suma_total', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('suma_directa', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'predominio_ent',
                'indexes': [models.Index(fields=['departamento', '-pct'], name='idx_pred_depto'), models.Index(fields=['-pct'], name='idx_pred_pct')],
            },
        ),
    ]
