# Generated by Django 6.1 on 2026-10-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_banderas_precalculadas_v34'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['nit_entidad'], name='idx_contrato_nitent'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['-valor_contrato'], name='idx_contrato_valor'),
        ),
    ]
